### ISSUE TITLE
Writing Korean IME

### ISSUE THREAD

**Issue by SergieGit** [halbae87/KoreanBasicIME#1]
Hello "halbae87"

I wondered if you were still active in developing Android IME.  I am looking for a Korean IME for my product and wondered if you would be interested in developing one for me

Thank you
Sergie

**Comment by halbae87** [comment]
it seems not an IME issue here.

Thanks for your suggestion, but I'm afraid I don't have much time to pay attention on it.
Well, I made this IME from Android SDK sample program and it inherited same license of the sample.
So you can use this source as you wish under same license agreement.

Good luck.
